### ISSUE TITLE
 Notify Services not being added

### ISSUE THREAD

**Issue by jamiezorin** [nebhead/garage-zero-v2#2] opened 2024-06-07 18:21 UTC
I've tried to add an email notification and was unable to save.  I've tried all services and no luck.  Any help would be appreciated.

**Comment by nebhead** [comment] 2024-06-07 19:55
Can you show me some screenshots or screencasts of what you see on your side?  Are you able to see your notification type in the list of notifications?  

![image](https://github.com/nebhead/garage-zero-v2/assets/19876886/ecfa8c54-a445-480f-bfdb-1690fab6dc4d)

What fields are you filling in for the e-mail type? 

![image](https://github.com/nebhead/garage-zero-v2/assets/19876886/d5ef5b89-f9dc-42c4-9480-a74bb8e0a885)

**Comment by jamiezorin** [comment] 2024-06-07 20:20
So here is snapshot after filling the fields, and I save changes and nothing appears. 
![2024-06-07 16_16_57-Add_Edit Notification Service — Mozilla Firefox](https://github.com/nebhead/garage-zero-v2/assets/94878040/f0de25a1-dede-4906-b7a5-8917c6995f8f)

![2024-06-07 16_19_41-Settings — Mozilla Firefox](https://github.com/nebhead/garage-zero-v2/assets/94878040/aca48192-8f4e-4521-873a-d09e0905a9ea)

**Comment by jamiezorin** [comment] 2024-06-07 20:37
One other thing I noticed 
![2024-06-07 16_33_46-Admin   Settings — Mozilla Firefox](https://github.com/nebhead/garage-zero-v2/assets/94878040/3c8f78a6-551b-4c67-b58a-31a6308a7aac)
![2024-06-07 16_34_10-500 Internal Server Error — Mozilla Firefox](https://github.com/nebhead/garage-zero-v2/assets/94878040/6903d628-87ad-4093-99a1-bdc3122a6322)
I cannot add a user, I get the following error, I'm using "2021-05-07-raspios-buster-armhf-lite" on a raspberry pi zero 2w.

**Comment by nebhead** [comment] 2024-06-07 22:38
> So here is snapshot after filling the fields, and I save changes and nothing appears. 

Just reproduced on my end and definitely will need to debug and get back to you on this one. 

> One other thing I noticed

Unfortunately, it is a known issue with the Raspberry Pi.  It seems that the encryption libraries I'm trying to use are not supported by the Pi currently and fail.  :(  I may need to disable this feature for now, until a suitable replacement can be made _or_ they start to support it.

**Comment by jamiezorin** [comment] 2024-06-07 23:20
Is it possible to use umail.py i used this on a few projects.
https://github.com/shawwwn/uMail/blob/master/umail.py

**Comment by nebhead** [comment] 2024-06-09 15:30
> Is it possible to use umail.py i used this on a few projects. https://github.com/shawwwn/uMail/blob/master/umail.py

TBH - I'm not likely going to update this particular script with a new mail script.  

The current mail script works fine, but the issue that we are seeing here is more to do with the WebUI not sending the right data back to the app.  I haven't had a chance to debug further, but this appears to be happening for all the different notify methods.  I'm not sure why this has recently broke, because it _used_ to work on previous versions.  Hopefully I will have time to debug more soon.

**Comment by jamiezorin** [comment] 2024-06-09 16:27
OK, understood.  I really appreciate all the hard work that has gone into this project.

**Comment by nebhead** [comment] 2024-06-24 22:07
OK... I think I have a fix for both issues.  I am testing and will update you as soon as I confirm it is working.

**Comment by nebhead** [comment] 2024-06-25 00:35
All fixed up, I think.  Would love if you could test and report back.  

https://github.com/nebhead/garage-zero-v2/releases/tag/v2.0.7

This version does require a fresh install because of some of the changes I have made to the installation script and what versions of python modules get installed.

**Comment by nebhead** [comment] 2024-06-25 23:50
Confirmed fixed from another user.  I'm going to close this issue.  Please feel free to open if you need any further help.

**Closed** 2024-06-25 23:50 UTC

**Comment by jamiezorin** [comment] 2024-06-26 11:40
Thank-you, I tested email last night all works.
